version: "3.7"
services:
  app:
    image: node:lts
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - "3000:3000"